CC := gcc
CFLAGS := -O3 -Wall -Wextra

SRCDIR := src
EXEDIR := exe

SRCS := $(wildcard $(SRCDIR)/06*.c)
LIBS := src/ising/lattice.c src/ising/metropolis.c lib/mt19937ar.c src/utils/correlations.c -lm

all: $(SRCS:$(SRCDIR)/06%.c=$(EXEDIR)/06%)

clean:
	rm -f $(EXEDIR)/06*

$(EXEDIR)/06%: $(SRCDIR)/06%.c
	$(CC) $(CFLAGS) $< $(LIBS) -o $@

.PHONY: all clean
