CC := gcc
CFLAGS := -O3 -Wall -Wextra

SRCDIR := src
LIBDIR := src/ising
EXEDIR := exe

SRCS := $(wildcard $(SRCDIR)/06*.c)
LIBS := $(shell find $(LIBDIR) -name "*.c") src/utils/correlations.c -lm

all: $(SRCS:$(SRCDIR)/06%.c=$(EXEDIR)/06%)

clean:
	rm -f $(EXEDIR)/06*

$(EXEDIR)/06%: $(SRCDIR)/06%.c
	$(CC) $(CFLAGS) $< $(LIBS) -o $@

.PHONY: all clean
