CC := gcc
CFLAGS := -O3 -Wall -Wextra

SRCDIR := src
EXEDIR := exe

SRCS := $(wildcard $(SRCDIR)/08*.c)
LIBS := lib/mt19937ar.c src/ctmp/gillespie.c -lm

all: $(SRCS:$(SRCDIR)/08%.c=$(EXEDIR)/08%)

clean:
	rm -f $(EXEDIR)/08*

$(EXEDIR)/08%: $(SRCDIR)/08%.c
	$(CC) $(CFLAGS) $< $(LIBS) -o $@

.PHONY: all clean
